### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Hao-HUST** [tudelft3d/3D_Urban_Mesh_Annotator#1]
Hi, thanks for sharing your effective tool.

When I tried to compile your code according to your instruction, the errors occurred as follow: 

`hao@hao-R8428-G11:~/project/kance/3D_Urban_Mesh_Annotator/src/build$ make
[  1%] Generating ui_LightingDialog.h
make[2]: *** No rule to make target '../resources/quick_introduction.png', needed by 'qrc_Polyhedron_3.cpp'。 停止。
CMakeFiles/Makefile2:746: recipe for target 'CMakeFiles/demo_framework_autogen.dir/all' failed
make[1]: *** [CMakeFiles/demo_framework_autogen.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

Do you have any suggestions about that?

Thanks!

**Comment by Hao-HUST** [comment]
I just replace the figure name from "quick_Introduction.png" to "quick_introduction.png".

**Comment by Hao-HUST** [comment]
Hi, I meet a new compile issue as follow:

`hao@hao-R8428-G11:~/project/kance/3D_Urban_Mesh_Annotator/src/build$ make
[  1%] Generating qrc_Polyhedron_3.cpp
[  2%] Automatic MOC for target demo_framework
[  3%] Built target demo_framework_autogen
[  4%] Generating Scene_group_item_moc.cpp
[  5%] Generating Scene_item_moc.cpp
[  6%] Generating Scene_item_rendering_helper_moc.cpp
[  7%] Generating TextRenderer_moc.cpp
[  7%] Generating Viewer_interface_moc.cpp
[  7%] Building CXX object CMakeFiles/demo_framework.dir/demo_framework_autogen/mocs_compilation.cpp.o
In file included from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/build/demo_framework_autogen/EWIEGA46WW/moc_Scene.cpp:9:0,
                 from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/build/demo_framework_autogen/mocs_compilation.cpp:2:
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/build/demo_framework_autogen/EWIEGA46WW/../../../Scene.h:99:7: error: ‘void Scene::SwitchRenderingMode(CGAL::Three::Viewer_interface*, int)’ marked ‘override’, but does not override
  void SwitchRenderingMode(CGAL::Three::Viewer_interface *, const int) Q_DECL_OVERRIDE;
       ^~~~~~~~~~~~~~~~~~~
CMakeFiles/demo_framework.dir/build.make:211: recipe for target 'CMakeFiles/demo_framework.dir/demo_framework_autogen/mocs_compilation.cpp.o' failed
make[2]: *** [CMakeFiles/demo_framework.dir/demo_framework_autogen/mocs_compilation.cpp.o] Error 1
CMakeFiles/Makefile2:360: recipe for target 'CMakeFiles/demo_framework.dir/all' failed
make[1]: *** [CMakeFiles/demo_framework.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

Any suggestions about that?

**Comment by WeixiaoGao** [comment]
I've updated the code, please try again.

**Comment by Hao-HUST** [comment]
Thanks for your effort, but the new errors have still occurred:
`hao@hao-R8428-G11:~/project/kance/3D_Urban_Mesh_Annotator/src/build$ make
[  1%] Generating ui_LightingDialog.h
[  2%] Generating qrc_Polyhedron_3.cpp
[  3%] Automatic MOC for target demo_framework
[  3%] Built target demo_framework_autogen
[  4%] Generating Scene_group_item_moc.cpp
[  5%] Generating Scene_item_moc.cpp
[  6%] Generating Scene_item_rendering_helper_moc.cpp
[  7%] Generating TextRenderer_moc.cpp
[  7%] Generating Viewer_interface_moc.cpp
[  7%] Building CXX object CMakeFiles/demo_framework.dir/demo_framework_autogen/mocs_compilation.cpp.o
[  8%] Building CXX object CMakeFiles/demo_framework.dir/Scene.cpp.o
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp: In member function ‘void Scene::SwitchRenderingMode(CGAL::Three::Viewer_interface*, int)’:
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:526:30: error: ‘TextureMode’ was not declared in this scope
   if (it->renderingMode() != TextureMode)
                              ^~~~~~~~~~~
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:526:30: note: suggested alternative: ‘QTextDecoder’
   if (it->renderingMode() != TextureMode)
                              ^~~~~~~~~~~
                              QTextDecoder
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp: In member function ‘void Scene::renderScene(const QList<int>&, CGAL::Three::Viewer_interface*, QMap<float, int>&, bool, int, bool, QOpenGLFramebufferObject*)’:
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:591:32: error: ‘TextureMode’ was not declared in this scope
     || item.renderingMode() == TextureMode || item.renderingMode() == TextureModePlusFlatEdges
                                ^~~~~~~~~~~
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:591:32: note: suggested alternative: ‘QTextDecoder’
     || item.renderingMode() == TextureMode || item.renderingMode() == TextureModePlusFlatEdges
                                ^~~~~~~~~~~
                                QTextDecoder
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:591:71: error: ‘TextureModePlusFlatEdges’ was not declared in this scope
     || item.renderingMode() == TextureMode || item.renderingMode() == TextureModePlusFlatEdges
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:592:32: error: ‘Emphasizing’ was not declared in this scope
     || item.renderingMode() == Emphasizing)
                                ^~~~~~~~~~~
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:612:121: error: no matching function for call to ‘CGAL::qglviewer::Camera::pointUnderPixel(QPoint&, bool&, int)’
 oint = viewer->camera()->pointUnderPixel(picked_pixel, found_tmp, viewer->devicePixelRatio()) - viewer->offset();
                                                                                             ^
In file included from /usr/local/include/CGAL/Qt/qglviewer.h:27:0,
                 from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.h:20,
                 from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:2:
/usr/local/include/CGAL/Qt/camera.h:425:7: note: candidate: CGAL::qglviewer::Vec CGAL::qglviewer::Camera::pointUnderPixel(const QPoint&, bool&) const
   Vec pointUnderPixel(const QPoint &pixel, bool &found) const;
       ^~~~~~~~~~~~~~~
/usr/local/include/CGAL/Qt/camera.h:425:7: note:   candidate expects 2 arguments, 3 provided
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp: In member function ‘void Scene::draw_aux(bool, CGAL::Three::Viewer_interface*)’:
/home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:765:114: error: no matching function for call to ‘CGAL::qglviewer::Camera::pointUnderPixel(QPoint&, bool&, int)’
 ec point = viewer->camera()->pointUnderPixel(picked_pixel, found, viewer->devicePixelRatio()) - viewer->offset();
                                                                                             ^
In file included from /usr/local/include/CGAL/Qt/qglviewer.h:27:0,
                 from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.h:20,
                 from /home/hao/project/kance/3D_Urban_Mesh_Annotator/src/Scene.cpp:2:
/usr/local/include/CGAL/Qt/camera.h:425:7: note: candidate: CGAL::qglviewer::Vec CGAL::qglviewer::Camera::pointUnderPixel(const QPoint&, bool&) const
   Vec pointUnderPixel(const QPoint &pixel, bool &found) const;
       ^~~~~~~~~~~~~~~
/usr/local/include/CGAL/Qt/camera.h:425:7: note:   candidate expects 2 arguments, 3 provided
CMakeFiles/demo_framework.dir/build.make:225: recipe for target 'CMakeFiles/demo_framework.dir/Scene.cpp.o' failed
make[2]: *** [CMakeFiles/demo_framework.dir/Scene.cpp.o] Error 1
CMakeFiles/Makefile2:360: recipe for target 'CMakeFiles/demo_framework.dir/all' failed
make[1]: *** [CMakeFiles/demo_framework.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Hao-HUST** [comment]
Update a new erros：
`/home/huawei/project/kance/3D_Urban_Mesh_Annotator/src/SMesh_type.h:11:66: fatal error: CGAL/Shape_detection_3/Region_growing/Region_growing.h: 没有那个文件或目录
compilation terminated.`

**Comment by WeixiaoGao** [comment]
Thank you for your efforts to test it on Linux. Currently, we have not tested it yet on Linux, if you succeeded, we can do the PR. In addition, please uses the CGAL we provide.

**Comment by LiangliangNan** [comment]
@WeixiaoGao Since we are using a modified version of CGAL, you should avoid using `find_package(CGAL)`. So please don't mention the dependence of CGAL and remove the following line

https://github.com/tudelft3d/3D_Urban_Mesh_Annotator/blob/d7344d9055f549c43b43fc28e9e9045aefa244b0/src/CMakeLists.txt#L61
